# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
system ? builtins.currentSystem
, lib
, fetchurl
, installShellFiles
, stdenvNoCC
}:
let
  shaMap = {
    x86_64-linux = "1xy4g8lg2klx5w6rxd4k3iha8f0x8jzja2bz18vzhwspph4jikdx";
    aarch64-linux = "0qcms4q1bi7hqcwk5xqm2j6ywjbywzh58ca74kqcg46r7l0ix7bx";
    x86_64-darwin = "1a41239df2ckrbyyyb9j112n7y9cq26f769w7cbn16kp7kd9qmxd";
    aarch64-darwin = "0zx9y7iy1hdj7pxs9zmkq9qhrr2xgcxhjxb5i6cdzl2y86zdbsl6";
  };

  urlMap = {
    x86_64-linux = "https://github.com/louiss0/javascript-package-delegator/releases/download/v1.0.0/javascript-package-delegator_1.0.0_linux_amd64.tar.gz";
    aarch64-linux = "https://github.com/louiss0/javascript-package-delegator/releases/download/v1.0.0/javascript-package-delegator_1.0.0_linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/louiss0/javascript-package-delegator/releases/download/v1.0.0/javascript-package-delegator_1.0.0_darwin_amd64.tar.gz";
    aarch64-darwin = "https://github.com/louiss0/javascript-package-delegator/releases/download/v1.0.0/javascript-package-delegator_1.0.0_darwin_arm64.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "javascript-package-delegator";
  version = "1.0.0";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./jpd $out/bin/jpd
  '';

  system = system;

  meta = {
    description = "A CLI for executing Javascript Package Manager Commands based on lock files. Supported's deno,bun, and all node package managers";
    license = lib.licenses.mit;

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
