run:
  timeout: 5m

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - ineffassign
    - gosimple
    - typecheck
    - revive
    - unparam
    - gofumpt
    - gocritic
    - prealloc
    - misspell
  disable:
    - lll

linters-settings:
  govet:
    enable:
      - shadow
  gofumpt:
    extra-rules: true

issues:
  exclude-use-default: false
  exclude-dirs:
    - vendor
    - .git
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec
