package main_test

import (
	"os"

	"github.com/louiss0/javascript-package-delegator/detect"
	. "github.com/onsi/ginkgo/v2"

	"github.com/stretchr/testify/assert"
)

var _ = Describe("Detect", func() {

	assert := assert.New(GinkgoT())

	Describe("Package Manager", func() {
		var tempDir string
		var originalDir string

		BeforeEach(func() {
			originalDir, _ = os.Getwd()
			tempDir, _ = os.MkdirTemp("", "jpd-test-*")
			os.Chdir(tempDir)
		})

		AfterEach(func() {
			os.Chdir(originalDir)
			os.RemoveAll(tempDir)
		})

		It("should detect deno from deno.lock", func() {

			os.WriteFile("deno.lock", []byte(`{}`), 0644)
			pkg, error := detect.DetectJSPacakgeManager()

			assert.NoError(error)

			assert.Equal(pkg, "deno")
			assert.True(true) // Placeholder
		})

		It("should detect deno from deno.json", func() {
			os.WriteFile("deno.json", []byte(`{}`), 0644)
			pkg, error := detect.DetectJSPacakgeManager()

			assert.NoError(error)

			assert.Equal(pkg, "deno")
		})

		It("should detect deno from deno.jsonc", func() {
			os.WriteFile("deno.jsonc", []byte(`{}`), 0644)
			pkg, error := detect.DetectJSPacakgeManager()

			assert.NoError(error)

			assert.Equal(pkg, "deno") // Would test actual detection here
		})

		It("should detect bun from bun.lockb", func() {
			os.WriteFile("bun.lockb", []byte(``), 0644)
			pkg, error := detect.DetectJSPacakgeManager()

			assert.NoError(error)

			assert.Equal(pkg, "bun")
		})

		It("should detect pnpm from pnpm-lock.yaml", func() {
			os.WriteFile("pnpm-lock.yaml", []byte(`lockfileVersion: 5.4`), 0644)
			pkg, error := detect.DetectJSPacakgeManager()

			assert.NoError(error)

			assert.Equal(pkg, "pnpm")
		})

		It("should detect yarn from yarn.lock", func() {
			os.WriteFile("yarn.lock", []byte(`# THIS IS AN AUTOGENERATED FILE`), 0644)
			pkg, error := detect.DetectJSPacakgeManager()

			assert.NoError(error)

			assert.Equal(pkg, "yarn")
		})

		It("should detect npm from package-lock.json", func() {
			pkg, error := detect.DetectJSPacakgeManager()

			assert.NoError(error)

			assert.Equal(pkg, "npm")
		})

		It("should default to npm when no lock files found", func() {
			pkg, error := detect.DetectJSPacakgeManager()

			assert.NoError(error)

			assert.Equal(pkg, "npm")
		})

		It("should prioritize deno over other package managers", func() {
			// Create multiple lock files
			os.WriteFile("deno.json", []byte(`{}`), 0644)
			os.WriteFile("package-lock.json", []byte(`{}`), 0644)
			os.WriteFile("yarn.lock", []byte(``), 0644)
			pkg, error := detect.DetectJSPacakgeManager()

			assert.NoError(error)

			assert.Equal("deno", pkg)
		})
	})

})
