# javascript-package-delegator

This project is called javascript-package-delegator.
It's a CLI that allows the user to exec javascript package manager commands based on the lock files associated with the project.
This CLI is written in Go. It's released by using Go Releaser.

// The user can download it using brew,scoop, winget or chocolatey.

.Tools
|===
| type | name
|
| utilities | samber/lo
| test runner | onsi/ginkgo
| assertion | testify/assert
|===


## Usage

[NOTE]
.This is a TDD project which means you test commands by running a test suite.
====


To test commands, you can run the following command:

```sh
ginkgo run
```

To watch files for changes and re-run tests:

```sh
ginkgo watch
```
====

### Writing Commands

When you create a new command, you should follow these steps:

. Create a new file in the `cmd` directory with the name of the command.
. In the file, make a called New{CommandName}Cmd function that returns the command you see after using `cobra-cli add`.
. In the `init()` 's `rootCmd.AddCommand()` Use the function you created in step 2.
. In the function write the flags and arguments for the command after the variable creation.
. Write tests for the command in the `javascript-package-delegator_suite_test.go` file.

TIP: Use the `cobra-cli add` command to create a new command.

NOTE: Remember to always add arguments to your commands.

CAUTION: Gingko will run tests in parallel by default.


## Project structure

```sh
├── cmd
│   └── root.go
├── cmd_test.go
├── cobra_cli_template_suite_test.go
├── custom_errors
│   └── root.go
├── custom_flags
│   └── root.go
├── go.mod
├── go.sum
├── LICENSE
├── main.go
├── README.adoc
|-- goreleaser.yaml
```

This project has the cmd package and two other packages.
The `custom_errors` and `custom_flags` package.
The custom errors package was created to created named errors.
The custom flags package is created for generic flags.

The custom_flags is filled with flags that are meant to be used in cobra's `cmd.Flags().Var()` methods.
To use them you must create each struct in a variable then use each variable as a reference to each function.
I decided to use the word `root.go` as the name of each file because it makes it clear that it's the main file.
