# This file was generated by GoReleaser. DO NOT EDIT.
cask "javascript-package-delegator" do
  desc "Software to create fast and easy drum rolls."
  homepage ""
  version "1.0.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "jpd"

  on_macos do
    on_intel do
      url "https://github.com/louiss0/javascript-package-delegator/releases/download/v1.0.0/javascript-package-delegator_1.0.0_darwin_amd64.tar.gz"
      sha256 "8b76cae6427af95b79304700d7775d090ccf790f74bb909346bb0e4edf0682a7"
    end
    on_arm do
      url "https://github.com/louiss0/javascript-package-delegator/releases/download/v1.0.0/javascript-package-delegator_1.0.0_darwin_arm64.tar.gz"
      sha256 "e4c17d96636b8771f3d9a9490caef8e17d7cddc2ffa525612dfb20558dc7a12a"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/louiss0/javascript-package-delegator/releases/download/v1.0.0/javascript-package-delegator_1.0.0_linux_amd64.tar.gz"
      sha256 "d0a7e045cfa94aadd750616c140a5aee40f041b074b25e7fd30110f26a80f051"
    end
    on_arm do
      url "https://github.com/louiss0/javascript-package-delegator/releases/download/v1.0.0/javascript-package-delegator_1.0.0_linux_arm64.tar.gz"
      sha256 "f4271b28b4f2f5740893f418221076ea4de4905f0c3037943af908d921831db3"
    end
  end

  # No zap stanza required
end
