# This file was generated by GoReleaser. DO NOT EDIT.
cask "javascript-package-delegator" do
  desc "Software to create fast and easy drum rolls."
  homepage ""
  version "1.0.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "jpd"

  on_macos do
    on_intel do
      url "https://github.com/louiss0/javascript-package-delegator/releases/download/v1.0.0/javascript-package-delegator_1.0.0_darwin_amd64.tar.gz"
      sha256 "6692a66313c6db4bb6a865aab45276adad743820ec47a96fc63637a039829aad"
    end
    on_arm do
      url "https://github.com/louiss0/javascript-package-delegator/releases/download/v1.0.0/javascript-package-delegator_1.0.0_darwin_arm64.tar.gz"
      sha256 "00cb8708c864c95b697760872e29a215d545387cb28ba1c6d9ef71c68d00929a"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/louiss0/javascript-package-delegator/releases/download/v1.0.0/javascript-package-delegator_1.0.0_linux_amd64.tar.gz"
      sha256 "87b1be580c6187043d2177b93fa28eb27473992e51110806349c9a31d5e3b69d"
    end
    on_arm do
      url "https://github.com/louiss0/javascript-package-delegator/releases/download/v1.0.0/javascript-package-delegator_1.0.0_linux_arm64.tar.gz"
      sha256 "bead7ca84bdf8d2704905784b85accc9f990c15049de1ac4dee50f69cab2f497"
    end
  end

  # No zap stanza required
end
